services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
      - ./backend/sql:/app/sql
    environment:
      - DB_PATH=/app/sql/app.db
    networks:
      - app-network  # Define a network for both services

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"  # Exposing frontend on port 80
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app-network  # Connect to the same network
    stdin_open: true
    tty: true

networks:
  app-network:  # Ensure both services are on the same Docker network
    driver: bridge